spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        notification_like_channel:
          name: notification_like_channel
        mentorship_channel:
          name: mentorship_channel
        project_channel:
          name: project_channel
        comment_channel:
          name: comment_channel


server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

achievements:
  title:
    love_everyone: love_everyone
    sensey: SENSEI
    businessman: BUSINESSMEN
    expert: EXPERT
app:
  async:
    executorBeanName: executor