spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement:
          name: achievement_channel
        follower:
          name: follower_channel
        team_channel:
          name: team_channel

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

achievement-service:
  achievement_manager: MANAGER

async:
  corePoolSize: 10
  maxPoolSize: 15
  queueCapacity: 1000
  threadName: Async-Executor-
